### ISSUE TITLE
LoafWallet App iOS balance issue

### ISSUE THREAD

**Issue by delta-59** [litecoin-foundation/loafwallet-ios-deprecated#41]
Hello, 

I have faced with a bug in your app. After update (even 2.0.1) I see zero LTC on my balance and can’t see my last transactions in the history. 
Even after clean install to a new device with restoring the wallet it shows the same result.

It’s very important for me to get it fixed ASAP.

**Comment by zahidkhan47** [comment]
I am also facing the same issue. Please resolved this issue.

**Comment by zahiir** [comment]
I also have the same issue please help us

**Comment by user90900** [comment]
SAME HERE with more than 20LTC!!! Please fix that asap! 

I have a real bad feeling right now.....

**Comment by delta-59** [comment]
Well guys, as far as I’m able to see developers of this wallet are not interested in satisfaction of their customers and don’t want to understand that such issues should be fixed ASAP. They just don’t care. 

Well, here is the solution: install the same wallet on android device of your friend and restore your wallet with the phrase. Then transfer your ltc to any other wallets like jaxx and forget about this terrible LoafWallet app with unresposible team. Shame on you, guys!

**Comment by zahidkhan47** [comment]
Yes I did the same 2 week back

Sent from my iPhone

On Dec 9, 2017, at 9:51 AM, delta-59 <notifications@github.com<mailto:notifications@github.com>> wrote:


Well guys, as far as I’m able to see developers of this wallet are not interested in satisfaction of their customers and don’t want to understand that such issues should be fixed ASAP. They just don’t care.

Well, here is the solution: install the same wallet on android device of your friend and restore your wallet with the phrase. Then transfer your ltc to any other wallets like jaxx and forget about this terrible LoafWallet app with unresposible team. Shame on you, guys!

**Comment by user90900** [comment]
Hello @zahidkhan47 
Thanks for the advice. Tried it with android, sync the network etc etc. Coins received BUT STILL NOT IN THE BALANCE!!! 
Terrible app which steal my 25 LTC! 
FIX THIS ASAP

**Comment by zahidkhan47** [comment]
Me and my friend recovered LTC using android Try on another device.

Sent from my iPhone

On Dec 9, 2017, at 3:05 PM, user90900 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @zahidkhan47<https://github.com/zahidkhan47>
Thanks for the advice. Tried it with android, sync the network etc etc. Coins received BUT STILL NOT IN THE BALANCE!!!
Terrible app which steal my 25 LTC!
FIX THIS ASAP

**Comment by losh11** [comment]
Maybe y’all should email the support email written inside the app.
Contact@loafwallet.org I can’t tell if some people here are blind, but this
repo is clearly marked deprecated and even has a link to the new repo. I
have notifications for this switched off.

**Comment by losh11** [comment]
Closing due to inactivity.
